[package]
name = "sophia_benchmark"
version = "0.3.1"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>", "Konrad Höffner"]
edition = "2021"

[workspace]
members = [".", ]

[dependencies]
#sophia = "0.7.2"
sophia = { version="0.8.0-alpha", git="https://github.com/pchampin/sophia_rs" }
time = "*"
regex = "1.7.0"
#hdt = "0.0.12"
hdt = { version="0.0.13-alpha", git="https://github.com/konradhoeffner/hdt" }
