[package]
name = "sophia_benchmark"
version = "0.3.0"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>", "Konrad Höffner"]
edition = "2021"

[workspace]
members = [".", ]

[dependencies]
sophia = "0.7.2"
time = "*"
regex =  "1.7.0"
hdt = "0.0.9"
